# Generated by Django 2.0.5 on 2018-05-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalweight',
            name='animals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_animal', to='api.Animal'),
            preserve_default=False,
        ),
    ]
